apiVersion: v1
kind: Service
metadata:
  name: sonar
  namespace: devops
  labels:
    app: sonar
spec:
  type: NodePort
  ports:
   - port: 30104
     protocol: TCP
     targetPort: 9000
     nodePort: 30104
     name: port-sonar
  selector:
   app: sonar